### ISSUE TITLE
(Firefox 123.0.1 (64-bit), Debian) Changing CSS of whole webpage content upon enabling the plugin.

### ISSUE THREAD

**Issue by serobon** [chloe-matt/sonastik#13]
This block of CSS interacts with whole webpage body:
![image](https://github.com/chloe-matt/sonastik/assets/145667981/37dad69e-088c-4b76-8c69-8f4592a4af42)

As I'm writing this issue, the color of the background is being overwritten by the` background-color: var(--mantine-color-body); ` line
![image](https://github.com/chloe-matt/sonastik/assets/145667981/98439b13-01e2-4118-b03a-f481c629b1a6)

This also messed up unicode emoji display(example):
Before enabling extension:
![image](https://github.com/chloe-matt/sonastik/assets/145667981/6ba5cc90-2423-4eaa-9791-2463832aad7f)

After:
![image](https://github.com/chloe-matt/sonastik/assets/145667981/e5fa1c6b-f985-483f-95f7-d2af38a53685)

I guess it forces browser to use a different emoji display?

**Comment by bepitulaz** [comment]
Thanks for reporting. I'm guessing the UI kit that I use is forcing it. I will take a look and fix it.

**Comment by bepitulaz** [comment]
Hi @serobon, the PR for this issue was merged. The new version 1.2.1 is already available on Firefox Add-on market. You can update your extension.
